const moviesList = [
  {
    title: '33 слова о дизайне',
    image: './dark-2/1.png',
    duration: '77',
    movieId: 1,
    isSaved: false,
  },
  {
    title: 'Киноальманах «100 лет дизайна»',
    image: './dark-2/2.png',
    duration: '77',
    movieId: 2,
    isSaved: true,
  },
  {
    title: 'В погоне за Бенкси',
    image: './dark-2/3.png',
    duration: '77',
    movieId: 3,
    isSaved: false,
  },
  {
    title: 'Баския: Взрыв реальности',
    image: './dark-2/4.png',
    duration: '77',
    movieId: 4,
    isSaved: false,
  },
  {
    title: 'Бег это свобода',
    image: './dark-2/5.png',
    duration: '77',
    movieId: 5,
    isSaved: false,
  },
  {
    title: 'Книготорговцы',
    image: './dark-2/6.png',
    duration: '77',
    movieId: 6,
    isSaved: true,
  },
  {
    title: 'Когда я думаю о Германии ночью',
    image: './dark-2/7.png',
    duration: '77',
    movieId: 7,
    isSaved: false,
  },
  {
    title: 'Gimme Danger: История Игги и The Stooges',
    image: './dark-2/8.png',
    duration: '77',
    movieId: 8,
    isSaved: false,
  },
  {
    title: 'Дженис: Маленькая девочка грустит',
    image: './dark-2/9.png',
    duration: '77',
    movieId: 9,
    isSaved: false,
  },
  {
    title: 'Соберись перед прыжком',
    image: './dark-2/10.png',
    duration: '77',
    movieId: 10,
    isSaved: false,
  },
  {
    title: 'Пи Джей Харви: A dog called money',
    image: './dark-2/11.png',
    duration: '77',
    movieId: 11,
    isSaved: false,
  },
  {
    title: 'По волнам: Искусство звука в кино',
    image: './dark-2/12.png',
    duration: '77',
    movieId: 12,
    isSaved: false,
  },
];

export default moviesList;
